// H:\DMA Hamim\DMA-Web-App\src\context\LanguageContext.tsx
import React, { createContext, useContext, useState } from 'react';
import { STORAGE_KEYS } from '../services/api.ts';

const enUS: Record<string, string> = {
  'title': 'MoreFish',
  'dma_technologies': 'DMA Technologies',
  'poultry_care': 'Poultry Care',
  'cattle_care': 'Cattle Care',
  'dhaka': 'Dhaka',
  'home': 'Home',
  'notifications': 'Notifications',
  'profile': 'Profile',
  'more': 'More',
  'not_now': 'Not Now',
  'login': 'Login',
  'please_login': 'Please, Login before continuing.',
  'live_data_monitoring': 'Live Data Monitoring',
  'fish_disease_detector': 'Fish Disease Detector',
  'pond_management': 'Pond Management',
  'feed_management': 'Feed Management',
  'fish_disease_treatment': 'Fish Disease Treatment',
  'live_consultancy': 'Live Consultancy',
  'fish_farm_marketplace': 'Fish Farm Marketplace',
  'fingerlings_marketplace': 'Fingerlings Marketplace',
  'grown_fish_sell': 'Grown Fish Sell',
  'fish_medicine_enzyme': 'Fish Medicine & Enzyme',
  'fcr_calculator': 'FCR Calculator',
  'nano_bubble_aeration_system': 'Nano Bubble Aeration System',
  'fish_pond_filtration_system': 'Fish Pond Filtration System',
  'fish_feed_marketplace': 'Fish Feed Marketplace',
  'training_workshop': 'Training & Workshop',
  'farm_management': 'Farm Management',
  'auto_aerator_connection': 'Auto Aerator Connection',
  'auto_feeder_connection': 'Auto Feeder Connection',
  'weather_forecast': 'Weather Forecast',
  'emergency_service': 'Emergency Service',
  'smart_khamari': 'Smart Khamari',
  'cluster_farming_club': 'Cluster Farming Club',
  'fish_farm_management_software': 'Fish Farm Management Software',
  'weekly_medicinal_records': 'Weekly Medicinal Records',
  'farm_financial_management': 'Farm Financial Management',
  'fish_growth_data_and_consultation': 'Fish Growth Data and Consultation',
  'farm_development_support': 'Farm Development Support',
  'fish_culture_system': 'Fish Culture System',
  'feed_management_system': 'Feed Management System',
  'cctv_surveillance': 'CCTV Surveillance',
  'aqua_news': 'Aqua News',
  'aqua_equipments_guide': 'Aqua Equipments Guide',
  'easy_accounting_solutions': 'Easy Accounting Solutions',
  'erp_solutions': 'ERP solutions',
  'sme_loan_solutions': 'SME Loan Solutions',
  'live_video_consultation': 'Live Video Consultation',
  'ras_aquaculture_system': 'RAS Aquaculture System',
  'ipras_aquaculture_system': 'IPRAS Aquaculture System',
  'fish_production_software': 'Fish Production Software',
  'high_density_fish_farming': 'High Density Fish Farming',
  'more_fish': 'What is more fish?',
  'core_problem': 'The Core Problem It Solves',
  'sensor_device': 'The Sensor Device',
  'dissolved_oxygen': 'Dissolved Oxygen (DO)',
  'ph_level': 'pH Level',
  'temperature': 'Temperature',
  'ammonia': 'Ammonia, Nitrite',
  'salinity': 'Salinity & TDS',
  'data_analyzer': 'Real-Time Data Analyzer',
  'live_dashboard': 'Live Dashboard',
  'smart_alerts': 'Smart Alerts & Notifications',
  'historical_data': 'Historical Data & Trends',
  'data_driven': 'Data-Driven Insights',
  'mortality': 'Prevent Mass Mortality',
  'reduced_losses': 'Reduced Losses',
  'feed_conversion': 'Optimized Feed Conversion',
  'about_app': 'Know about More Fish',
  'monitoring': 'Real time monitoring',
  'food index': 'Time index of providing food',
  'production_plan': 'Production plan',
  'inventory': 'Inventory management',
  'analysis': 'Analysis and apply',
  'interface': 'Usable Interface',
  'technology': 'Sustainable Technology',
  'choose': 'Q1.Why choose us?',
  'device': 'Q2.How can I get sample IoT devices?',
  'price': 'Q3.How can I get the price?',
  'cost': 'Q4.Are your pre-orders free or need cost?',
  'iphone': 'Q5.Do you have apps for IPhone?',
  'dashboard': 'Q6.Do you have web dashboard?',
  'website': 'Q7.Do you have any website?',
  'services': 'Q8.Do you provide services all over Bangladesh?',
  'internationally': 'Q9.Can you provide services internationally?',
  'contact': 'Q10.How can I contact you?',
  'office': 'Q11.Where is your office?',
  'parameter': 'Ideal Water Quality Parameters',
  'farming': 'Steps for Fish Farming',
  'pond': 'Pond Selection Criteria',
  'guide': 'Pond Preparation Guide',
  'types': 'Types of Feed',
  'guidelines': 'Feed Selection Guidelines',
  'quantity': 'Feeding Time and Quantity',
  'methods': 'Feeding Methods',
  'relationship': 'Relationship Between Water & Feed Management',
  'feeding_tips': 'Special Feeding Tips',
  'ration': 'Feed Conversion Ratio (FCR)',
  'calculator': 'Feed Recruitment Calculator',
  'first_name': 'First Name',
  'last_name': 'Last Name',
  'address': 'Address',
  'email': 'Email',
  'phone_number': 'Phone Number',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'submit': 'Submit',
  'registration': 'Registration',
  'enter_first_name': 'Enter your first name',
  'enter_last_name': 'Enter your last name',
  'enter_address': 'Enter your Address',
  'enter_email': 'Enter your email',
  'enter_valid_email': 'Enter a valid email',
  'enter_password': 'Enter your password',
  'password_length_error': 'Password must be at least 5 characters',
  'confirm_password_error': 'Confirm your password',
  'password_mismatch': 'Passwords do not match',
  'welcome_back': 'Welcome back.',
  'invalid_credentials': 'Oops! Invalid login credentials.',
  'dont_have_account': "Don't have an account?",
  'register': ' Register',
  'forgot_password_q': 'Forgot Password?',
  'change_password': 'Change Password',
  'logout': 'Logout',
  'social': 'Social',
  'registration_error': 'Oops! Invalid registration info.',
  'registration_success': 'Registered Successfully ✅',
  'waiting_for_live_data': 'Waiting for live data...',
  'select_device': 'Select device',
  'select_farm': 'Select Farm',
  'auto_mode': 'Auto Mode',
  'manual_control_disabled': 'Manual control is disabled while Automation is ON.',
  'auto_cleaner': 'Auto-Cleaner',
  'on': 'On',
  'off': 'Off',
  'last_run': 'Last Run',
  'cleaner_schedule_note': 'Every day at 2:00 PM Bangladesh time, the cleaner turns ON.',
  'try_again': 'Try Again',
  'switch_controls': 'Switch Controls',
  'note': 'Note',
  'warning': 'Warning',
  'poultry_param_note': 'Note: The parameters are changeable according to installation of device.',
  'cattle_param_note': 'Note: Values reflect the latest data from your farm devices.',
  'no_data': 'No Data',
  'failed_to_load': 'Failed to load',
  'faq_menu': 'FAQ',
  'about_app_menu': 'About App',
  'about_device_menu': 'About Device',
  'automation_settings_menu': 'Automation Settings',
  'language': 'Language',
  'english': 'English',
  'bangla': 'Bangla',
  'poultry_disease_treatment': 'Poultry Disease Treatment',
  'chicks_marketplace': 'Chicks Marketplace',
  'poultry_feed_marketplace': 'Poultry Feed Marketplace',
  'auto_feeder': 'Auto Feeder',
  'auto_water_system': 'Auto Water System',
  'financial_management': 'Financial Management',
  'cattle_disease_treatment': 'Cattle Disease Treatment',
  'cattle_marketplace': 'Cattle Marketplace',
  'cattle_feed_marketplace': 'Cattle Feed Marketplace',
  'sunlight': 'Sunlight',
  'air_temp': 'Air Temp',
  'humidity': 'Humidity',
  'pharma_care': 'Pharma Care',
  'feed_conversion_ratio': 'Feed Conversion Ratio',
  'total_feed_amount': 'Total Feed Amount (kg)',
  'total_weight_gain': 'Total Weight Gain (kg)',
  'calculate': 'Calculate',
  'clear': 'Clear',
  'result': 'Result',
  'no_assets_found': 'No assets found for this account.',
  'enter_numeric_values': 'Enter valid numeric values.',
  'values_greater_than_zero': 'Values must be greater than zero.',
  'asset_not_available': 'Asset not available for calculation.',
  'missing_auth_token': 'Missing authorization token.',
  'fcr_value_missing': 'FCR value missing in response.',
  'fcr_calc_failed': 'FCR calculation failed.',
  'calculating': 'Calculating...',
  'feed_requirement_calculator': 'Feed Requirement Calculator',
  'daily_feed_estimate': 'Daily feed estimate by fish size',
  'total_body_weight': 'Total Body Weight (kg)',
  'fry_fingerlings': 'Fry / Fingerlings',
  'medium_size': 'Medium Size',
  'market_size': 'Market Size',
  'of_body_weight': 'of body weight',
  'no_image_selected': 'No image selected',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'detect_disease': 'Detect Disease',
  'detecting': 'Detecting...',
  'no_notifications': 'No notifications yet.',
  'feature_coming_soon': 'This feature is currently not implemented and will be coming soon.',
  'service_coming_soon': 'Service is coming soon',
  'new_version_available': 'A new version is available! Please update to continue using the app smoothly.',
  'update': 'Update',
  'clear sky': 'Clear Sky',
  'few clouds': 'Few Clouds',
  'scattered clouds': 'Scattered Clouds',
  'broken clouds': 'Broken Clouds',
  'shower rain': 'Shower Rain',
  'rain': 'Rain',
  'thunderstorm': 'Thunderstorm',
  'snow': 'Snow',
  'mist': 'Mist',
  'drizzle': 'Drizzle',
  'overcast clouds': 'Overcast Clouds',
  'light rain': 'Light Rain',
  'low': 'Low',
  'medium': 'Medium',
  'high': 'High',
  'Dhaka': 'Dhaka',
  'Mymensingh': 'Mymensingh',
  'Naogaon': 'Naogaon',
  'Bagerhat': 'Bagerhat',
  'Rajshahi': 'Rajshahi',
  'Chapai Nawabganj': 'Chapai Nawabganj',
  'Nawabganj': 'Nawabganj',
  'call_now': 'Call Now',
  'chat_expert': 'Chat with Expert',
  'expert_panel': 'Fishery Experts & Doctors Panel',
  'premium_consultation': 'Premium Video Consultation',
  'feeder_status': 'Auto Feeder Status',
  'feeder_online': 'Feeder Online',
  'feeder_offline': 'Feeder Offline',
  'no_feeder_device': 'No Auto Feeder hardware paired with this pond.',
  'feeder_schedule': 'Feeding Schedule',
  'add_schedule': 'Add Schedule',
  'manual_feed_trigger': 'Trigger Manual Feed Cycle',
  'smart_khamari_club': 'Smart Khamari Club – MoreFish Premium Members Network',
  'membership_tiers': 'Membership Tiers',
  'join_club': 'Join Club',
  'filtration_system': 'Pond Filtration System',
  'ammonia_level': 'Ammonia (NH3) Level',
  'nitrite_level': 'Nitrite Level',
  'mechanical_filter': 'Mechanical Filter',
  'biological_filter': 'Biological Filter',
  'view_filtration_guide': 'How to Build a Filtration System (RAS)',
};

const bnBD: Record<string, string> = {
  'title': 'আরো মাছ - MoreFish',
  'dma_technologies': 'ডিএমএ টেকনোলজিস (DMA Technologies)',
  'poultry_care': 'পোল্ট্রি কেয়ার',
  'cattle_care': 'ক্যাটেল কেয়ার',
  'dhaka': 'ঢাকা',
  'home': 'হোম',
  'notifications': 'নোটিফিকেশন',
  'profile': 'প্রোফাইল',
  'more': 'আরো',
  'not_now': 'এখন নয়',
  'login': 'লগইন',
  'please_login': 'অনুগ্রহ করে, আগে লগইন করুন।',
  'live_data_monitoring': 'লাইভ ডাটা মনিটরিং',
  'fish_disease_detector': 'মাছের রোগ শনাক্তকারী',
  'pond_management': 'পুকুর ব্যবস্থাপনা',
  'feed_management': 'খাদ্য ব্যবস্থাপনা',
  'fish_disease_treatment': 'মাছের রোগের চিকিৎসা',
  'live_consultancy': 'লাইভ পরামর্শ',
  'fish_farm_marketplace': 'মাছের খামার বাজার',
  'fingerlings_marketplace': 'মাছের পোনা বাজার',
  'grown_fish_sell': 'বড় মাছ বিক্রয়',
  'fish_medicine_enzyme': 'মাছের ওষুধ ও এনজাইম',
  'fcr_calculator': 'এফসিআর ক্যালকুলেটর',
  'nano_bubble_aeration_system': 'ন্যানো বাবল এয়ারেশন সিস্টেম',
  'fish_pond_filtration_system': 'ফিশ পন্ড ফিল্ট্রেশন সিস্টেম',
  'fish_feed_marketplace': 'মাছের খাবারের বাজার',
  'training_workshop': 'প্রশিক্ষণ ও কর্মশালা',
  'farm_management': 'চাষের ব্যবস্থাপনা',
  'auto_aerator_connection': 'স্বয়ংক্রিয় এয়ারেটর সংযোগ',
  'auto_feeder_connection': 'স্বয়ংক্রিয় ফিডার সংযোগ',
  'weather_forecast': 'আবহাওয়া পূর্বাভাস',
  'emergency_service': 'জরুরি সেবা',
  'smart_khamari': 'স্মার্ট খামারী',
  'cluster_farming_club': 'ক্লাস্টার ফার্মিং ক্লাব',
  'fish_farm_management_software': 'মাছের খামার ব্যবস্থাপনা সফটওয়্যার',
  'weekly_medicinal_records': 'সাপ্তাহিক ওষুধ সংক্রান্ত রেকর্ড',
  'farm_financial_management': 'খামারের আর্থিক ব্যবস্থাপনা',
  'fish_growth_data_and_consultation': 'মাছের বৃদ্ধির তথ্য এবং পরামর্শ',
  'farm_development_support': 'খামার উন্নয়ন সহায়তা',
  'fish_culture_system': 'মাছ চাষ ব্যবস্থাপনা',
  'feed_management_system': 'চারা/খাদ্য ব্যবস্থাপনা ব্যবস্থা',
  'cctv_surveillance': 'সিসিটিভি নজরদারি',
  'aqua_news': 'জলচাষ সংবাদ',
  'aqua_equipments_guide': 'জলচাষ সরঞ্জাম নির্দেশিকা',
  'easy_accounting_solutions': 'সহজ হিসাব-নিকাশ সমাধান',
  'erp_solutions': 'ইআরপি সমাধান',
  'sme_loan_solutions': 'ক্ষুদ্র ও মাঝারি উদ্যোগ ঋণ সমাধান',
  'live_video_consultation': 'সরাসরি ভিডিও পরামর্শ',
  'ras_aquaculture_system': 'আরএএস জলচাষ ব্যবস্থা',
  'ipras_aquaculture_system': 'আইপিআরএএস জলচাষ ব্যবস্থা',
  'fish_production_software': 'মাছ উৎপাদন সফটওয়্যার',
  'high_density_fish_farming': 'উচ্চ ঘনত্বে মাছ চাষ',
  'more_fish': 'আরও মাছ কী?',
  'core_problem': 'মূল সমস্যা যা এটি সমাধান করে',
  'sensor_device': 'সেন্সর ডিভাইস',
  'dissolved_oxygen': 'দ্রবীভূত অক্সিজেন (DO)',
  'ph_level': 'পিএইচ মাত্রা',
  'temperature': 'তাপমাত্রা',
  'ammonia': 'অ্যামোনিয়া, নাইট্রাইট',
  'salinity': 'লবণাক্ততা ও মোট দ্রবীভূত কঠিন পদার্থ',
  'data_analyzer': 'রিয়েল-টাইম ডেটা বিশ্লেষক',
  'live_dashboard': 'লাইভ ড্যাশবোর্ড',
  'smart_alerts': 'স্মার্ট সতর্কতা ও নোটিফিকেশন',
  'historical_data': 'ঐতিহাসিক তথ্য ও প্রবণতা',
  'data_driven': 'তথ্যভিত্তিক অন্তর্দৃষ্টি',
  'mortality': 'বৃহৎ মৃত্যুহার প্রতিরোধ করা',
  'reduced_losses': 'ক্ষতির হ্রাস',
  'feed_conversion': 'সর্বোত্তম খাবার রূপান্তর',
  'about_app': 'আরো মাছ (More Fish) অ্যাপ সম্পর্কে জানুন',
  'monitoring': 'রিয়েল-টাইম মনিটরিং',
  'food index': 'মাছের খাদ্য দেয়ার সময়সূচী',
  'production_plan': 'উৎপাদন পরিকল্পনা',
  'inventory': 'ইনভেন্টরি ব্যবস্থাপনাঃ',
  'analysis': 'বিশ্লেষণ ও এর কার্যকরি প্রয়োগ',
  'interface': 'ব্যবহার-বান্ধব ইন্টারফেস',
  'technology': 'টেকসই প্রযুক্তি',
  'choose': 'Q1.আপনাদের কেন পচন্দ করব?',
  'device': 'Q2.আমি কিবাবে IoT ডিভাইস পাব?',
  'price': 'Q3.আমি কিভাবে দাম জানতে পারব?',
  'cost': 'Q4.ফ্রি অরডার দেয়া যায় কিনা?',
  'iphone': 'Q5.IPhone এর জন্য অ্যাপ আছে কিনা?',
  'dashboard': 'Q6.Web dashboard আছে কিনা?',
  'website': 'Q7.Website আছে কিনা?',
  'services': 'Q8.আপনারা কি সারা বাংলাদেশে সেবা দেন?',
  'internationally': 'Q9.আপনারা কি internationally সেবা দেন?',
  'contact': 'Q10.আপনাদের সাথে কিবাবে যোগাযোগ করব?',
  'office': 'Q11.আপনাদের অফিস কোথায়?',
  'parameter': 'আদর্শ পানির গুণগত মান',
  'farming': 'মাছ চাষের ধাপ',
  'pond': 'পুকুর নির্বচনের মানদন্ড',
  'guide': 'পুকুর তৈরির ধারনা',
  'types': 'ফিডের প্রকারভেদ',
  'guidelines': 'ফিড নির্বাচন পদ্ধতি',
  'quantity': 'ফিডদেওয়ার সময় ও পরিমান',
  'methods': 'ফিডিং পদ্ধতি',
  'relationship': 'पानी ও ফিড ব্যবস্থাপনার মধে সম্প্ররক',
  'feeding_tips': 'বিশেষ ফিডিং ধারনা',
  'ration': 'ফিডের অনুপাত (FCR)',
  'calculator': 'ফিড ক্যালকুলেটর',
  'first_name': 'প্রথম নাম',
  'last_name': 'শেষ নাম',
  'address': 'ঠিকানা',
  'email': 'ইমেইল',
  'phone_number': 'ফোন নম্বর',
  'password': 'পাসওয়ার্ড',
  'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
  'submit': 'জমা দিন',
  'registration': 'নিবন্ধন',
  'enter_first_name': 'আপনার প্রথম নাম লিখুন',
  'enter_last_name': 'আপনার শেষ নাম লিখুন',
  'enter_address': 'আপনার ঠিকানা লিখুন',
  'enter_email': 'আপনার ইমেইল লিখুন',
  'enter_valid_email': 'সঠিক ইমেইল লিখুন',
  'enter_password': 'আপনার পাসওয়ার্ড লিখুন',
  'password_length_error': 'পাসওয়ার্ড অন্তত ৫ অক্ষরের হতে হবে',
  'confirm_password_error': 'পাসওয়ার্ড নিশ্চিত করুন',
  'password_mismatch': 'পাসওয়ার্ড মিলেনি',
  'welcome_back': 'আপনাকে স্বাগতম।',
  'invalid_credentials': 'দুঃখিত! ভুল লগইন তথ্য।',
  'dont_have_account': 'অ্যাকাউন্ট নেই?',
  'register': ' নিবন্ধন করুন',
  'forgot_password_q': 'পাসওয়ার্ড ভুলে গেছেন?',
  'change_password': 'পাসওয়ার্ড পরিবর্তন',
  'logout': 'লগআউট',
  'social': 'সো্যাল',
  'registration_error': 'দুঃখিত! ❌ ভুল নিবন্ধন তথ্য।',
  'registration_success': 'নিবন্ধন সফল হয়েছে ✅',
  'waiting_for_live_data': 'লাইভ ডাটার জন্য অপেক্ষা করা হচ্ছে...',
  'select_device': 'ডিভাইস নির্বাচন করুন',
  'select_farm': 'ফার্ম নির্বাচন করুন',
  'auto_mode': 'অটো মোড',
  'manual_control_disabled': 'অটোমেশন চালু থাকায় ম্যানুয়াল নিয়ন্ত্রণ বন্ধ আছে।',
  'auto_cleaner': 'অটো-ক্লিনার',
  'on': 'চালু',
  'off': 'বন্ধ',
  'last_run': 'সর্বশেষ চালনা',
  'cleaner_schedule_note': 'প্রতিদিন বাংলাদেশ সময় দুপুর ২:০০ টায় ক্লিনার চালু হয়।',
  'try_again': 'আবার চেষ্টা করুন',
  'switch_controls': 'সুইচ কন্ট্রোল',
  'note': 'নোট',
  'warning': 'সতর্কবার্তা',
  'poultry_param_note': 'নোট: ডিভাইসের ইনস্টলেশন অনুযায়ী প্যারামিটারগুলি পরিবর্তনযোগ্য।',
  'cattle_param_note': 'নোট: মানগুলি আপনার খামার ডিভাইস থেকে লেটেস্ট তথ্য প্রতিফলিত করে।',
  'no_data': 'কোনো তথ্য নেই',
  'failed_to_load': 'লোড হতে ব্যর্থ হয়েছে',
  'faq_menu': 'সাধারণ জিজ্ঞাসা (FAQ)',
  'about_app_menu': 'অ্যাপ সম্পর্কে',
  'about_device_menu': 'ডিভাইস সম্পর্কে',
  'automation_settings_menu': 'অটোমেশন সেটিংস',
  'language': 'ভাষা',
  'english': 'English',
  'bangla': 'বাংলা',
  'poultry_disease_treatment': 'পোল্ট্রি রোগের চিকিৎসা',
  'chicks_marketplace': 'বাচ্চার বাজার',
  'poultry_feed_marketplace': 'পোল্ট্রি খাদ্যের বাজার',
  'auto_feeder': 'স্বয়ংক্রিয় ফিডার',
  'auto_water_system': 'স্বয়ংক্রিয় পানি ব্যবস্থা',
  'financial_management': 'আর্থিক ব্যবস্থাপনা',
  'cattle_disease_treatment': 'গবাদি পশুর রোগ ও চিকিৎসা',
  'cattle_marketplace': 'গবাদি পশুর বাজার',
  'cattle_feed_marketplace': 'গবাদি পশুর খাদ্যের বাজার',
  'sunlight': 'সূর্যালোক',
  'air_temp': 'বায়ুর তাপমাত্রা',
  'humidity': 'আর্দ্রতা',
  'pharma_care': 'ফার্মা কেয়ার',
  'feed_conversion_ratio': 'ফিড কনভার্সন রেশিও (FCR)',
  'total_feed_amount': 'মোট খাদ্যের পরিমাণ (কেজি)',
  'total_weight_gain': 'মোট ওজন বৃদ্ধি (কেজি)',
  'calculate': 'হিসাব করুন',
  'clear': 'মুছে ফেলুন',
  'result': 'ফলাফল',
  'no_assets_found': 'এই অ্যাকাউন্টের জন্য কোনো পুকুর পাওয়া যায়নি।',
  'enter_numeric_values': 'সঠিক সংখ্যাগত মান লিখুন।',
  'values_greater_than_zero': 'মান অবশ্যই শূন্যের চেয়ে বেশি হতে হবে।',
  'asset_not_available': 'হিসাব করার জন্য পুকুর পাওয়া যায়নি।',
  'missing_auth_token': 'অথোরাইজেশন টোকেন নেই।',
  'fcr_value_missing': 'সার্ভার রেসপন্সে FCR মান নেই।',
  'fcr_calc_failed': 'FCR হিসাব করতে ব্যর্থ হয়েছে।',
  'calculating': 'হিসাব করা হচ্ছে...',
  'feed_requirement_calculator': 'খাদ্য প্রয়োজন ক্যালকুলেটর',
  'daily_feed_estimate': 'মাছের আকার অনুযায়ী দৈনিক খাদ্য অনুমান',
  'total_body_weight': 'মোট দেহের ওজন (কেজি)',
  'fry_fingerlings': 'পোনা / ফিঙ্গারলিং',
  'medium_size': 'মাঝারি আকার',
  'market_size': 'বাজারজাত আকার',
  'of_body_weight': 'দেহের ওজনের',
  'no_image_selected': 'কোনো ছবি নির্বাচন করা হয়নি',
  'camera': 'ক্যামেরা',
  'gallery': 'গ্যালারি',
  'detect_disease': 'রোগ শনাক্ত করুন',
  'detecting': 'শনাক্ত করা হচ্ছে...',
  'no_notifications': 'এখনও কোনো নোটিফিকেশন নেই।',
  'feature_coming_soon': 'এই ফিচারটি বর্তমানে নেই এবং শীঘ্রই যুক্ত করা হবে।',
  'service_coming_soon': 'সেবাটি শীঘ্রই আসছে',
  'new_version_available': 'একটি নতুন সংস্করণ উপলব্ধ! অ্যাপটি সাবলীলভাবে ব্যবহার চালিয়ে যেতে অনুগ্রহ করে আপডেট করুন।',
  'update': 'আপডেট',
  'clear sky': 'পরিষ্কার আকাশ',
  'few clouds': 'কিছু মেঘ',
  'scattered clouds': 'বিক্ষিপ্ত মেঘ',
  'broken clouds': 'ভাঙ্গা মেঘ',
  'shower rain': 'বৃষ্টি',
  'rain': 'বৃষ্টি',
  'thunderstorm': 'বজ্রঝড়',
  'snow': 'তুষারপাত',
  'mist': 'কুয়াশা',
  'drizzle': 'গুঁড়ি গুঁড়ি বৃষ্টি',
  'overcast clouds': 'মেঘাচ্ছন্ন আকাশ',
  'light rain': 'হালকা বৃষ্টি',
  'low': 'কম',
  'medium': 'মাঝারি',
  'high': 'বেশি',
  'Dhaka': 'ঢাকা',
  'Mymensingh': 'ময়মনসিংহ',
  'Naogaon': 'নওগাঁ',
  'Bagerhat': 'বাগেরহাট',
  'Rajshahi': 'রাজশাহী',
  'Chapai Nawabganj': 'চাঁপাইনবাবগঞ্জ',
  'Nawabganj': 'নবাবগঞ্জ',
  'call_now': 'কল করুন',
  'chat_expert': 'হোয়াটসঅ্যাপে চ্যাট করুন',
  'expert_panel': 'মৎস্য বিশেষজ্ঞ এবং চিকিৎসকদের প্যানেল',
  'premium_consultation': 'প্রিমিয়াম ভিডিও পরামর্শ',
  'feeder_status': 'স্বয়ংক্রিয় ফিডার স্ট্যাটাস',
  'feeder_online': 'ফিডার অনলাইন',
  'feeder_offline': 'ফিডার অফলাইন',
  'no_feeder_device': 'এই পুকুরের সাথে কোনো স্বয়ংক্রিয় ফিডার সংযুক্ত নেই।',
  'feeder_schedule': 'ফিডিং সময়সূচী',
  'add_schedule': 'সময়সূচী যোগ করুন',
  'manual_feed_trigger': 'ম্যানুয়ালি ফিডিং শুরু করুন',
  'smart_khamari_club': 'স্মার্ট খামারী ক্লাব – আরোমাছ প্রিমিয়াম মেম্বার্স নেটওয়ার্ক',
  'membership_tiers': 'সদস্যপদ প্ল্যানসমূহ',
  'join_club': 'ক্লাবে যোগ দিন',
  'filtration_system': 'পুকুর ফিল্ট্রেশন সিস্টেম',
  'ammonia_level': 'অ্যামোনিয়া (NH3) লেভেল',
  'nitrite_level': 'নাইট্রাইট লেভেল',
  'mechanical_filter': 'মেকানিক্যাল ফিল্টার',
  'biological_filter': 'বায়োলজিক্যাল ফিল্টার',
  'view_filtration_guide': 'কীভাবে একটি ফিল্ট্রেশন সিস্টেম (RAS) তৈরি করবেন',
};

type Language = 'en' | 'bn';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEYS.LANG);
    return (saved === 'bn' || saved === 'en') ? saved : 'en';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem(STORAGE_KEYS.LANG, newLang);
  };

  const t = (key: string): string => {
    const dict = lang === 'bn' ? bnBD : enUS;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLang must be used within LanguageProvider');
  return context;
};
